CREATE TABLE IF NOT EXISTS portfolios (
    id CHAR(36) PRIMARY KEY,  
    user_id VARCHAR NOT NULL,
    name VARCHAR NOT NULL,
    base_currency VARCHAR(10) NOT NULL,
    total_value NUMERIC(18, 2) DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);